name: Terraform Apply (infra)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity echo
        run: echo "YAML is valid and steps run"
